const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const load=async n=>(await fetch(`data/${n}.json`)).json();
const [nodes,edges,clusters,sources,bridges,routes,meta]=await Promise.all(['concepts','relations','clusters','sources','bridges','featured-routes','meta'].map(load));
const byId=new Map(nodes.map(n=>[n.id,n])); const sourceById=new Map(sources.map(s=>[s.id,s]));
$('#meta').innerHTML=`${meta.concepts} concepts · ${meta.relations} relations<br>${meta.sources} local source capsules · SymPy build ${meta.sympyBuildVersion}`;
$$('#tabs button').forEach(b=>b.onclick=()=>{$$('#tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab)); if(b.dataset.tab==='map') resize();});

// graph
const canvas=$('#graph'),ctx=canvas.getContext('2d'); let W=0,H=0,scale=.72,ox=0,oy=0,selected='sacred-computations',drag=false,last={x:0,y:0},activeCluster='all';
const clusterColors={root:'#f0c96b',ratios:'#d7b65b',sequences:'#59c2b2',number:'#74a6d7',geometry:'#d8756f',transforms:'#b89ae4',dynamics:'#e178a5',symbolic:'#9d86df',code:'#b3d673'};
function resize(){const r=canvas.getBoundingClientRect(); canvas.width=Math.max(1,r.width*devicePixelRatio);canvas.height=Math.max(1,r.height*devicePixelRatio);W=r.width;H=r.height;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);draw();}
new ResizeObserver(resize).observe(canvas);
const world=(x,y)=>({x:(x-W/2-ox)/scale,y:(y-H/2-oy)/scale}); const screen=(x,y)=>({x:W/2+ox+x*scale,y:H/2+oy+y*scale});
function visible(n){return activeCluster==='all'||n.cluster===activeCluster||n.id===selected}
function draw(){ctx.clearRect(0,0,W,H); const sel=byId.get(selected); const near=new Set(); if(sel){for(const e of edges)if(e.source===selected)near.add(e.target);else if(e.target===selected)near.add(e.source)}
 for(const e of edges){const a=byId.get(e.source),b=byId.get(e.target);if(!a||!b||!visible(a)||!visible(b))continue;const A=screen(a.x,a.y),B=screen(b.x,b.y);let alpha=selected&&(e.source===selected||e.target===selected)?.9:.17;let color=e.kind==='source-backed'?'#d7b65b':e.kind==='derived'?'#59c2b2':e.kind==='implementation'?'#9d86df':'#70747c';ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=(e.source===selected||e.target===selected)?2.2:1;if(e.kind==='implementation')ctx.setLineDash([6,5]);else if(e.kind==='curated')ctx.setLineDash([2,5]);else ctx.setLineDash([]);ctx.stroke();}
 ctx.setLineDash([]); for(const n of nodes){if(!visible(n))continue;const p=screen(n.x,n.y); const is=n.id===selected; const dim=selected&&!is&&!near.has(n.id);ctx.globalAlpha=dim?.20:1;ctx.beginPath();ctx.arc(p.x,p.y,is?10:6,0,Math.PI*2);ctx.fillStyle=clusterColors[n.cluster]||'#bbb';ctx.fill();if(is){ctx.strokeStyle='#fff4c4';ctx.lineWidth=2;ctx.stroke()} if(scale>.5||is){ctx.font=(is?'600 13px':'11px')+' system-ui';ctx.fillStyle='#e8e5da';ctx.fillText(n.title,p.x+10,p.y+4)}}ctx.globalAlpha=1;}
function hit(mx,my){let best=null,bd=18;for(const n of nodes){if(!visible(n))continue;const p=screen(n.x,n.y),d=Math.hypot(mx-p.x,my-p.y);if(d<bd){best=n;bd=d}}return best}
canvas.addEventListener('pointerdown',e=>{drag=true;last={x:e.offsetX,y:e.offsetY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;ox+=e.offsetX-last.x;oy+=e.offsetY-last.y;last={x:e.offsetX,y:e.offsetY};draw()});canvas.addEventListener('pointerup',e=>{const moved=Math.hypot(e.offsetX-last.x,e.offsetY-last.y);drag=false;const n=hit(e.offsetX,e.offsetY);if(n&&moved<8)selectNode(n.id)});canvas.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.2,Math.min(2.4,scale*Math.exp(-e.deltaY*.001)));draw()},{passive:false});
function selectNode(id){selected=id;renderInspector();draw();}
Object.entries({all:{label:'All'},...clusters}).forEach(([k,v])=>{const s=document.createElement('span');s.className='chip'+(k==='all'?' active':'');s.textContent=v.label;s.onclick=()=>{activeCluster=k;$$('#clusterFilters .chip').forEach(x=>x.classList.remove('active'));s.classList.add('active');draw()};$('#clusterFilters').append(s)});
function score(n,q){q=q.toLowerCase();const hay=[n.title,n.summary,n.formula,...n.aliases,...n.tags].join(' ').toLowerCase();if(n.title.toLowerCase().includes(q))return 10;if(hay.includes(q))return 5;let i=0;for(const c of hay)if(c===q[i])i++;return i===q.length?1:0}
function doSearch(){const q=$('#search').value.trim();const box=$('#searchResults');box.innerHTML='';if(!q)return;nodes.map(n=>[n,score(n,q)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,16).forEach(([n])=>{const d=document.createElement('div');d.className='searchItem';d.innerHTML=`<strong>${n.title}</strong><span class="small">${n.formula||n.cluster}</span>`;d.onclick=()=>selectNode(n.id);box.append(d)})} $('#search').oninput=doSearch;
function renderInspector(){const n=byId.get(selected);const rel=edges.filter(e=>e.source===n.id||e.target===n.id);const srcs=n.sources.map(id=>sourceById.get(id)).filter(Boolean);$('#inspector').innerHTML=`<div class="eyebrow">${clusters[n.cluster]?.label||n.cluster}</div><div class="nodeTitle">${n.title}</div><p>${n.summary}</p>${n.formula?`<div class="formula">${n.formula}</div>`:''}<div>${n.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div>${n.bridgeAvailable?`<p><a href="#" id="openBridge">Open executable SymPy bridge →</a></p>`:''}<h3>Relations</h3>${rel.map(e=>{const other=byId.get(e.source===n.id?e.target:e.source);return `<div class="rel"><div><a href="#" data-node="${other.id}">${other.title}</a></div><strong>${e.relation}</strong><div class="kind">${e.kind}</div><div class="small">${e.why||''}</div></div>`}).join('')}<div class="sourceLinks"><h3>Source capsules</h3>${srcs.length?srcs.map(s=>`<a href="public/${s.localPath}" target="_blank">${s.title}</a>`).join(''):'<span class="muted">No direct capsule mapped; relation is derived/structural.</span>'}</div>`;$$('[data-node]').forEach(a=>a.onclick=e=>{e.preventDefault();selectNode(a.dataset.node)});const ob=$('#openBridge');if(ob)ob.onclick=e=>{e.preventDefault();openBridge(n.bridge);$$('#tabs button').find(x=>x.dataset.tab==='bridges').click()}}
renderInspector();

// bridges
const bridgeNodeIds=nodes.filter(n=>n.bridgeAvailable).map(n=>n.id);for(const id of bridgeNodeIds){const n=byId.get(id),d=document.createElement('div');d.className='bridgeItem';d.dataset.bridge=id;d.innerHTML=`<strong>${n.title}</strong><div class="small">${bridges[id].kind}</div>`;d.onclick=()=>openBridge(id);$('#bridgeList').append(d)}
function openBridge(id){if(!id||!bridges[id])return;$$('.bridgeItem').forEach(x=>x.classList.toggle('active',x.dataset.bridge===id));const n=byId.get(id),b=bridges[id];const codes=['sympy','python','c','javascript','rust'].filter(k=>b[k]);$('#bridgeDetail').innerHTML=`<div class="eyebrow">SYMBOLIC → EXECUTABLE</div><h2>${n?.title||id}</h2><p>${n?.summary||''}</p>${b.formula?`<div class="formula">${b.formula}</div>`:''}${b.polynomial?`<div class="formula">polynomial: ${b.polynomial}<br>exact root: ${b.exact}<br>≈ ${b.decimal}<br>residual: ${b.residual}</div>`:''}${b.companionMatrix?`<h3>State / companion matrix</h3><pre>${b.companionMatrix.map(r=>r.join('   ')).join('\n')}</pre>`:''}<div class="pipeline">${(b.pipeline||[]).map((x,i)=>`${i?'<i>→</i>':''}<span>${x}</span>`).join('')}</div><div class="codegrid">${codes.map(k=>`<div class="codecard"><h4>${k}</h4><pre>${escapeHtml(String(b[k]))}</pre></div>`).join('')}</div>`}
function escapeHtml(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))} if(bridgeNodeIds[0])openBridge(bridgeNodeIds[0]);

// matrix
const rows=nodes.filter(n=>n.id!=='sacred-computations');const matrixCols=[['Formula',n=>!!n.formula],['Sources',n=>n.sources.length>0],['SymPy bridge',n=>n.bridgeAvailable],['Matrix lane',n=>edges.some(e=>(e.source===n.id||e.target===n.id)&&(e.source==='matrix-recurrence'||e.target==='matrix-recurrence'||e.source==='sympy-matrices'||e.target==='sympy-matrices'))],['Code lane',n=>edges.some(e=>(e.source===n.id||e.target===n.id)&&(e.source==='codegen'||e.target==='codegen'||e.kind==='implementation'))]];$('#matrixTable').innerHTML=`<div class="tableWrap"><table><thead><tr><th>Concept</th><th>Cluster</th>${matrixCols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(n=>`<tr><td>${n.title}</td><td>${clusters[n.cluster].label}</td>${matrixCols.map(c=>`<td class="${c[1](n)?'yes':'no'}">${c[1](n)?'●':'·'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;

// routes
function routeNames(ids){return ids.map(id=>byId.get(id)?.title||id)}routes.forEach(r=>{const d=document.createElement('div');d.className='routeCard';d.innerHTML=`<strong>${r.title}</strong><p class="small">${r.note}</p><div class="routePath">${routeNames(r.nodes).map((x,i)=>`${i?'<b>→</b>':''}<span>${x}</span>`).join('')}</div>`;$('#routeCards').append(d)});for(const sel of [$('#routeFrom'),$('#routeTo')])for(const n of nodes){const o=document.createElement('option');o.value=n.id;o.textContent=n.title;sel.append(o)}$('#routeFrom').value='pell';$('#routeTo').value='rust-target';
function shortest(s,t){const adj=new Map(nodes.map(n=>[n.id,[]]));for(const e of edges){adj.get(e.source).push(e.target);if(!e.directed)adj.get(e.target).push(e.source)}const q=[s],prev=new Map([[s,null]]);while(q.length){const u=q.shift();if(u===t)break;for(const v of adj.get(u)||[])if(!prev.has(v)){prev.set(v,u);q.push(v)}}if(!prev.has(t))return[];const out=[];for(let x=t;x;x=prev.get(x))out.push(x);return out.reverse()}$('#routeGo').onclick=()=>{const r=shortest($('#routeFrom').value,$('#routeTo').value);$('#routeResult').innerHTML=r.length?`<div class="routeCard"><div class="routePath">${routeNames(r).map((x,i)=>`${i?'<b>→</b>':''}<span>${x}</span>`).join('')}</div></div>`:'<p>No route.</p>'};

// sources
const stats=Object.entries(meta.sourceGroups).map(([k,v])=>`<span>${k}: ${v}</span>`).join('');$('#sourceStats').className='sourceStats';$('#sourceStats').innerHTML=stats;
function renderSources(){const q=$('#sourceSearch').value.toLowerCase();const arr=sources.filter(s=>!q||s.title.toLowerCase().includes(q)||s.group.includes(q)).slice(0,400);$('#sourceList').innerHTML=arr.map(s=>`<div class="sourceItem"><div class="group">${s.group}</div><div><strong><a href="public/${s.localPath}" target="_blank">${s.title}</a></strong><span class="small">${s.source||'local capture'}</span></div><code>${s.sha256.slice(0,12)}</code></div>`).join('')}$('#sourceSearch').oninput=renderSources;renderSources();
